INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Henry","Timothy","Walters","neque.nullam@yahoo.org","+79278852921","1983-04-22",28,"21 6193303",1,"arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum","https://youtube.com/sub/cars?ad=115"),
  ("Orlando","Thomas","Lott","ut@google.couk","89183903836","1984-02-09",20,"97 5333226",2,"dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros","http://youtube.com/site?g=1"),
  ("Jolene","Brian","Nieves","elit.dictum@protonmail.net","+79550466195","1995-01-20",40,"92 3961330",3,"Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo","http://youtube.com/sub/cars?q=4"),
  ("Zachary","Charles","Gates","lobortis.quam@protonmail.couk","+79166761335","1986-05-18",31,"15 4090336",4,"turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum","http://rutube.ru/sub?k=0"),
  ("Kelly","Nolan","Clayton","donec.fringilla@hotmail.org","89768415528","2002-04-11",38,"83 5439126",5,"Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit,","http://youtube.com/group/9?client=g"),
  ("Oscar","Graiden","Mckinney","arcu.ac@aol.couk","89944824144","1989-06-30",25,"52 9219386",6,"purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet","https://youtube.com/en-us?search=1&q=de"),
  ("Steel","Tucker","Hinton","mi.enim.condimentum@aol.edu","89463888825","1997-08-28",37,"67 0628115",7,"Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a,","http://youtube.com/one?q=0"),
  ("Byron","Vincent","Potts","amet.ante@hotmail.com","89324358844","1994-05-28",37,"00 8243087",8,"Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin","http://rutube.ru/fr?ab=441&aad=2"),
  ("Kadeem","Hasad","Bonner","duis.ac.arcu@outlook.net","89175451858","1987-09-30",35,"88 6634135",9,"magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer","http://rutube.ru/fr?client=g"),
  ("Aristotle","Joshua","Richard","eget.massa@outlook.couk","89567388988","2004-04-20",28,"12 3621571",10,"Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare","http://rutube.ru/sub?page=1&offset=1");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Maggie","Graham","Sutton","elit@outlook.org","89684063807","1998-05-08",32,"76 1755145",11,"nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes,","https://youtube.com/one?g=1"),
  ("Jared","Keefe","Clark","quisque.nonummy.ipsum@google.couk","+79693231011","2001-01-28",22,"38 2668802",12,"euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis","https://youtube.com/one?q=0"),
  ("Garth","Dolan","Miller","nisl@protonmail.com","89777142773","1990-12-01",23,"67 0873841",13,"faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel,","http://rutube.ru/user/110?q=4"),
  ("Aurelia","Arsenio","Morse","vitae.semper@outlook.ca","89718532031","1989-03-23",20,"13 0367708",14,"a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus","https://youtube.com/sub/cars?str=se"),
  ("Howard","Keefe","Craig","fermentum.vel.mauris@outlook.net","+79818473734","1998-03-15",33,"68 8177178",15,"faucibus orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue.","https://rutube.ru/site?search=1&q=de"),
  ("Rose","Erich","Huber","vehicula.aliquet@yahoo.com","89277176327","1989-05-14",19,"64 0782046",16,"nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus.","http://youtube.com/sub/cars?q=4"),
  ("Eric","Lev","Tillman","quam.quis@protonmail.edu","89551144554","1992-09-09",25,"38 5502505",17,"at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu","https://rutube.ru/en-us?k=0"),
  ("Cheryl","Patrick","Owen","lacinia.vitae@google.ca","+79794876155","1989-02-09",39,"85 6116666",18,"quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus","http://youtube.com/fr?q=4"),
  ("Lael","Prescott","Crosby","fermentum@yahoo.ca","89731288418","1997-08-09",26,"70 2025525",19,"pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi","https://rutube.ru/sub?search=1"),
  ("Igor","Roth","Kidd","ut.ipsum@hotmail.couk","89887876259","1984-04-28",19,"79 6946299",20,"lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa.","http://rutube.ru/sub?search=1");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Moana","Timon","Blair","augue@google.com","+79831453718","1984-01-25",24,"75 2510272",21,"accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere","http://youtube.com/user/110?gi=100"),
  ("Hammett","Wesley","Hoover","elit.erat.vitae@yahoo.edu","+79684810948","2001-06-11",20,"75 1187863",22,"adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc","http://rutube.ru/sub/cars?q=0"),
  ("Kylan","Xavier","Acevedo","mauris@yahoo.ca","+79025481366","1987-11-23",23,"25 7287263",23,"et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat.","https://rutube.ru/fr?client=g"),
  ("Illana","Walker","Serrano","nunc.sed@aol.edu","+79763786807","1988-10-07",36,"94 1554731",24,"tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat","http://youtube.com/fr?q=0"),
  ("William","Barclay","Kinney","tempus.eu@hotmail.edu","+79579165721","2000-08-25",34,"91 8521655",25,"amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula.","https://rutube.ru/en-ca?ad=115"),
  ("Connor","Channing","Simmons","nullam@yahoo.net","89518238481","1988-03-29",40,"26 3714363",26,"ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.","http://rutube.ru/user/110?p=8"),
  ("Ainsley","Alvin","Park","massa.vestibulum.accumsan@aol.ca","89684708536","1996-03-20",34,"29 9244103",27,"semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc","http://rutube.ru/en-us?str=se"),
  ("Vance","Linus","Stark","et.lacinia.vitae@yahoo.org","+79652805628","1996-12-20",37,"07 9181431",28,"mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero","http://youtube.com/group/9?k=0"),
  ("Lance","Galvin","Haley","mollis@protonmail.edu","+79846984301","2000-08-22",28,"52 6421672",29,"turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante","https://rutube.ru/one?gi=100"),
  ("Kimberly","Zeph","Long","vivamus.rhoncus@hotmail.org","+79311433922","1987-07-22",27,"78 8294358",30,"leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida","https://youtube.com/site?p=8");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Eagan","Nathaniel","Hickman","luctus.felis@google.net","+79164932970","1999-09-04",35,"54 0201232",31,"in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,","http://rutube.ru/group/9?p=8"),
  ("Olivia","Dolan","Franks","non.lorem@yahoo.org","+79897433605","1992-08-15",20,"61 9624863",32,"egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et","https://youtube.com/one?ad=115"),
  ("Willa","Hamish","Kirby","quis.diam@yahoo.com","+79297443547","1986-08-13",34,"45 7649162",33,"fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem,","https://youtube.com/en-us?client=g"),
  ("Felix","Jelani","O'brien","malesuada.vel@outlook.couk","+79846448867","1986-08-03",33,"86 1135757",34,"massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla.","https://rutube.ru/sub/cars?page=1&offset=1"),
  ("Lael","Anthony","Duncan","turpis.aliquam@aol.org","+79550313963","2002-10-16",24,"25 6230218",35,"consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at","http://rutube.ru/sub/cars?q=4"),
  ("Nita","Caleb","Frye","porttitor.scelerisque@yahoo.net","+79948340536","1985-07-15",29,"56 8730005",36,"tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est,","http://rutube.ru/fr?q=0"),
  ("Erin","Alden","Ellis","amet.ornare@google.ca","+79888517633","1989-01-12",30,"11 6412652",37,"magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus","http://rutube.ru/sub?q=0"),
  ("Fulton","Uriel","Mccarty","praesent@icloud.com","+79788706111","1995-08-01",32,"11 6974726",38,"conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,","https://rutube.ru/group/9?gi=100"),
  ("Reece","Wayne","Hess","hymenaeos@outlook.ca","89537932714","2002-08-27",37,"40 7030755",39,"vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat,","https://rutube.ru/one?p=8"),
  ("Seth","Logan","Hayes","sit.amet.metus@protonmail.couk","89224687889","1990-04-22",25,"14 6374536",40,"Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit","http://rutube.ru/sub/cars?k=0");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Zeph","Bruce","Downs","dictum.eu.placerat@google.edu","89173527335","1991-11-13",25,"52 6454177",41,"pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec","https://rutube.ru/sub?p=8"),
  ("Summer","Macon","Knapp","mauris.rhoncus@protonmail.org","89651506767","1997-01-06",35,"33 0634253",46pokFKiNH52ZK1W64wsWVH1Z2t2gueuTcj2xWWp3QCtAWGhC4m6WsQ7Sou6AtzEzrfTkoPy2ibAyA9vWsdsnRscRcX7bVy placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non","http://rutube.ru/sub/cars?q=11"),
  ("Samantha","Flynn","Stevenson","scelerisque.neque.nullam@google.edu","+79443041328","1990-06-22",24,"51 6292574",43,"vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse","http://rutube.ru/site?str=se"),
  ("Yeo","Brendan","Schmidt","facilisi.sed@google.net","89218744422","1990-03-08",38,"24 4994768",44,"non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat","http://rutube.ru/en-ca?client=g"),
  ("Shannon","Evan","Fleming","malesuada.integer@aol.net","89248727457","1999-07-31",45,"34 8331250",45,"urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas","http://rutube.ru/one?k=0"),
  ("Colton","Cain","French","nec.orci@aol.com","89542461296","1990-10-07",23,"52 2553171",46,"Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis.","http://youtube.com/group/9?q=4"),
  ("Evangeline","Cameron","Smith","dolor.tempus@outlook.edu","+79869875574","1994-03-16",28,"14 7174483",47,"iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor","https://youtube.com/fr?search=1"),
  ("Felicia","Camden","Pittman","suscipit.est@icloud.com","+79978762736","1988-03-07",36,"52 5665339",48,"et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci,","https://rutube.ru/user/110?q=test"),
  ("Yuri","Howard","Harding","luctus.et@yahoo.edu","89334488862","1984-07-10",23,"72 6047771",46pokFKiNH52ZK1W64wsWVH1Z2t2gueuTcj2xWWp3QCtAWGhC4m6WsQ7Sou6AtzEzrfTkoPy2ibAyA9vWsdsnRscRcX7bVyru/en-us?client=g"),
  ("Desirae","Akeem","Pickett","eu@aol.org","+79134411453","2000-05-01",22,"02 8078177",50,"ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id","https://rutube.ru/en-us?q=4");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Erich","Jamal","Andrews","et.tristique.pellentesque@google.ca","89466148210","1988-05-12",24,"58 1363225",51,"Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede,","http://rutube.ru/en-ca?client=g"),
  ("Zahir","Drew","Wolf","vivamus.euismod@aol.ca","89910585089","1994-02-07",22,"23 9441204",52,"velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,","https://rutube.ru/sub?g=1"),
  ("Zelda","Emery","Solis","etiam.imperdiet@yahoo.net","+79452796434","1985-02-25",23,"34 7076122",53,"metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan","https://rutube.ru/fr?page=1&offset=1"),
  ("Lev","Gannon","Lynn","amet.faucibus@outlook.com","+79877909515","2002-01-22",28,"69 2133089",54,"eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in","https://rutube.ru/group/9?q=4"),
  ("Calvin","Adam","Ray","turpis.aliquam@outlook.org","89758423156","1998-12-13",29,"61 8788263",55,"orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque","http://rutube.ru/user/110?q=4"),
  ("Demetria","Mohammad","Ellison","parturient.montes@icloud.couk","89631137278","1988-04-20",39,"97 4382666",56,"velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget","https://youtube.com/user/110?gi=100"),
  ("Griffith","Anthony","Horton","ornare.facilisis@hotmail.net","89678716856","1990-01-02",22,"97 4382666",57," erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque","http://youtube.com/group/9?p=8"),
  ("Reese","Logan","Vincent","suspendisse.non@protonmail.edu","+79681346545","1992-01-10",27,"30 2635567",58,"mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed","http://rutube.ru/fr?client=g"),
  ("Quinn","Barry","Oneil","justo.eu@icloud.com","+79287113312","2004-03-14",38,"16 8381347",59,"mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut","https://youtube.com/en-us?q=4"),
  ("Alden","Joshua","Velasquez","aliquet.libero@yahoo.edu","+79211943921","1991-08-29",24,"00 5181397",60,"mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi","http://rutube.ru/fr?page=1&offset=1");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Courtney","Allistair","Hood","dictum.magna@yahoo.org","89572634779","1984-02-21",31,"57 3605961",61,"blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum","http://youtube.com/en-ca?page=1&offset=1"),
  ("Xander","Malcolm","Rios","at@icloud.couk","+79619625044","1988-07-30",19,"82 5300218",62,"Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris","http://rutube.ru/en-ca?ab=441&aad=2"),
  ("Sylvester","Kaseem","Garza","pede.malesuada@aol.ca","89672922721","1994-06-23",20,"77 6872549",63,"quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis","http://youtube.com/group/9?gi=100"),
  ("Emma","Merritt","Cardenas","et@icloud.com","89836794404","2000-05-09",29,"84 8266637",64,"Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor","http://rutube.ru/sub/cars?q=4"),
  ("Emery","Orson","Atkinson","at.egestas.a@aol.com","89339942316","1983-05-05",35,"27 2361578",65,"scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed","https://rutube.ru/sub/cars?q=4"),
  ("Aquila","Fitzgerald","Kirby","mauris.erat.eget@aol.ca","+79554445875","2002-06-26",38,"91 3217721",66,"dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.","http://rutube.ru/fr?k=0"),
  ("Elaine","Russell","Dyer","eros.proin@icloud.com","+79524530451","1988-04-15",31,"57 1246272",67,"viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo","http://rutube.ru/user/110?k=0"),
  ("Morgan","Cain","Hanson","pellentesque@google.com","89241351048","1988-08-06",38,"22 2182585",68,"sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis","https://youtube.com/sub?k=0"),
  ("Selma","Magee","Nieves","nec.cursus.a@google.org","+79085323052","1992-03-04",20,"22 2982585",69, "dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim,","http://youtube.com/group/9?ad=115"),
  ("Nero","Scott","Simpson","bibendum.donec@hotmail.net","+79214120666","2004-01-14",26,"63 1778325",70,"lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie","http://youtube.com/site?q=test");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Kathleen","Neville","Wiley","sed@google.net","89483930578","1992-10-26",22,"84 7021236",71,"Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,","http://rutube.ru/sub?search=1&q=de"),
  ("Ronan","Fuller","Francis","proin.velit.sed@icloud.org","89264872424","1997-03-02",24,"71 3507763",72,"in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo.","https://rutube.ru/settings?search=1"),
  ("Rosalyn","Aaron","Lee","suspendisse.eleifend@aol.org","89645101350","2000-05-12",25," iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis","https://rutube.ru/group/9?q=4"),
  ("Abraham","Harlan","Orr","cursus.et@outlook.com","89169820756","1992-11-15",36,"32 2731192",74,"lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi","http://rutube.ru/sub?p=8"),
  ("Brody","Carter","Pugh","sit.amet@google.couk","89425785825","2000-01-29",27,"61 4638477",75,"Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus","https://youtube.com/en-us?g=1"),
  ("Darryl","Griffith","Buckner","montes.nascetur@aol.net","89543848457","2004-04-25",23,"21 6668454",76,"dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut","http://youtube.com/sub?p=8"),
  ("Yoshio","Joseph","Gill","vivamus@icloud.com","+79634872774","1993-09-20",39,"14 5125772",77,"amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.","http://youtube.com/one?k=0"),
  ("Quintessa","Lucius","Wilkins","nec.luctus@outlook.org","+79352374563","1991-09-10",35,"68 5667544",78,"tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut","http://youtube.com/site?q=test"),
  ("Grady","Griffin","Welch","elit@hotmail.ca","+79816642794","1986-04-23",20,"66 1421836",79,"Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus","https://youtube.com/en-us?q=test"),
  ("Teegan","Brandon","Farmer","vitae.erat@icloud.ca","89635787213","1990-05-31",20,"66 1421836",79, "sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo.","http://youtube.com/settings?search=1");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Kelsey","Raja","Swanson","metus.vivamus@aol.couk","+79334751047","1996-04-02",23,"38 1262194",81,"ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis","http://rutube.ru/sub?k=0"),
  ("Keegan","Xavier","Brown","non@hotmail.org","+79674121138","1997-04-15",19,"80 0415965",82,"a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc","https://youtube.com/en-us?str=se"),
  ("Denton","Alfonso","Clemons","mollis.nec.cursus@icloud.ca","+79515423015","2001-11-22",30,"94 4825754",83,"a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec","http://rutube.ru/settings?search=1&q=de"),
  ("Joan","Wylie","Bradshaw","mauris.suspendisse@hotmail.couk","+79813479954","1991-10-19",24,"98 7348602",84,"mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim","http://youtube.com/sub/cars?client=g"),
  ("Asher","Honorato","Combs","diam@yahoo.com","+79568532231","2001-11-17",29,"98 2142442",85,"porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam","http://youtube.com/en-us?search=1&q=de"),
  ("Callie","Colt","Nash","quisque.fringilla@outlook.net","+79771323641","1995-01-29",36,"95 1168616",86,"Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi.","https://youtube.com/group/9?p=8"),
  ("Dolan","Sean","Mccarty","maecenas@yahoo.edu","+79775441958","1983-06-26",30,"02 0856634",87,"eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor","https://youtube.com/fr?page=1&offset=1"),
  ("Flynn","Micah","Church","ipsum.suspendisse@aol.ca","89421983888","2004-01-16",30,"75 5097841",88,"aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem","https://youtube.com/site?q=0"),
  ("Harrison","Grady","Oliver","feugiat.lorem@yahoo.net","+79555233122","2004-05-29",30,"75 5097841",88,"bVyProin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada","http://rutube.ru/user/110?client=g"),
  ("Ezekiel","Dominic","Kirby","vitae.velit@aol.org","+79432852296","1988-06-03",22,"81 5470242",90,"dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam","http://rutube.ru/site?q=4");
INSERT INTO `sportsmen` (`firstname`,`middle_name`,`lastname`,`email`,`phone`,`birthday`,`age`,`passport`,`position`,`bio`,`video_link`)
VALUES
  ("Hope","Carlos","Rivera","ut.pellentesque@hotmail.org","+79477922828","1991-03-05",36,"63 1452373",91,"at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla","http://rutube.ru/user/110?q=0"),
  ("Wynter","Raja","Odom","id@outlook.net","+79280725626","1993-10-14",37,"95 3137781",92,"Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a,","http://youtube.com/one?search=1"),
  ("MacKenzie","Channing","Montgomery","at.egestas@icloud.ca","89626212262","1993-03-26",31,"18 5535549",93,"fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,","https://youtube.com/user/110?search=1&q=de"),
  ("Joelle","Dorian","Byrd","laoreet.lectus.quis@icloud.com","89842387468","1996-02-26",30,"49 1629358",94,"augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a","https://rutube.ru/group/9?ad=115"),
  ("Edward","Dorian","Petty","odio@yahoo.org","+79180766436","2002-04-22",21,"65 5188319",95,"odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est","http://rutube.ru/user/110?client=g"),
  ("Garth","Mufutau","Page","massa.quisque@aol.org","+79664554870","1999-03-22",37,"24 3874145",96,"nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,","http://youtube.com/fr?ad=115"),
  ("Willow","Walker","Gilmore","ipsum@icloud.org","+79153676289","1997-08-29",36,"75 7408578",97,"adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis","http://rutube.ru/group/9?ad=115"),
  ("Lucas","Dillon","Hughes","lacinia.mattis@icloud.edu","89641911462","1986-07-31",26,"46 6788750",98,"magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,","http://youtube.com/en-ca?search=1"),
  ("Jeremy","Jacob","Hensley","velit@protonmail.com","+79133065638","1983-04-20",36,"67 2353377",99,"montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.","https://rutube.ru/en-ca?ab=441&aad=2"),
  ("Kirsten","Russell","Fields","aliquet@protonmail.com","+79176276372","1983-09-17",33,"46 1052774",100,"Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet","http://rutube.ru/user/110?k=0");


UPDATE sportsmen SET position = '35' WHERE id = 1;
UPDATE sportsmen SET position = '15' WHERE id = 2;
UPDATE sportsmen SET position = '8' WHERE id = 3;
UPDATE sportsmen SET position = '84' WHERE id = 4;
UPDATE sportsmen SET position = '7' WHERE id = 5;
UPDATE sportsmen SET position = '57' WHERE id = 6;
UPDATE sportsmen SET position = '9' WHERE id = 7;
UPDATE sportsmen SET position = '61' WHERE id = 8;
UPDATE sportsmen SET position = '22' WHERE id = 9;
UPDATE sportsmen SET position = '91' WHERE id = 10;
UPDATE sportsmen SET position = '95' WHERE id = 11;
UPDATE sportsmen SET position = '27' WHERE id = 12;
UPDATE sportsmen SET position = '50' WHERE id = 13;
UPDATE sportsmen SET position = '44' WHERE id = 14;
UPDATE sportsmen SET position = '72' WHERE id = 15;
UPDATE sportsmen SET position = '88' WHERE id = 16;
UPDATE sportsmen SET position = '73' WHERE id = 17;
UPDATE sportsmen SET position = '51' WHERE id = 18;
UPDATE sportsmen SET position = '85' WHERE id = 19;
UPDATE sportsmen SET position = '34' WHERE id = 20;
UPDATE sportsmen SET position = '31' WHERE id = 21;
UPDATE sportsmen SET position = '42' WHERE id = 22;
UPDATE sportsmen SET position = '16' WHERE id = 23;
UPDATE sportsmen SET position = '21' WHERE id = 24;
UPDATE sportsmen SET position = '58' WHERE id = 25;
UPDATE sportsmen SET position = '36' WHERE id = 26;
UPDATE sportsmen SET position = '6' WHERE id = 27;
UPDATE sportsmen SET position = '20' WHERE id = 28;
UPDATE sportsmen SET position = '93' WHERE id = 29;
UPDATE sportsmen SET position = '99' WHERE id = 30;
UPDATE sportsmen SET position = '3' WHERE id = 31;
UPDATE sportsmen SET position = '82' WHERE id = 32;
UPDATE sportsmen SET position = '19' WHERE id = 33;
UPDATE sportsmen SET position = '4' WHERE id = 34;
UPDATE sportsmen SET position = '33' WHERE id = 35;
UPDATE sportsmen SET position = '75' WHERE id = 36;
UPDATE sportsmen SET position = '17' WHERE id = 37;
UPDATE sportsmen SET position = '32' WHERE id = 38;
UPDATE sportsmen SET position = '60' WHERE id = 39;
UPDATE sportsmen SET position = '5' WHERE id = 40;
UPDATE sportsmen SET position = '92' WHERE id = 41;
UPDATE sportsmen SET position = '59' WHERE id = 42;
UPDATE sportsmen SET position = '26' WHERE id = 43;
UPDATE sportsmen SET position = '30' WHERE id = 44;
UPDATE sportsmen SET position = '12' WHERE id = 45;
UPDATE sportsmen SET position = '37' WHERE id = 46;
UPDATE sportsmen SET position = '41' WHERE id = 47;
UPDATE sportsmen SET position = '79' WHERE id = 48;
UPDATE sportsmen SET position = '10' WHERE id = 49;
UPDATE sportsmen SET position = '55' WHERE id = 50;
UPDATE sportsmen SET position = '94' WHERE id = 51;
UPDATE sportsmen SET position = '46' WHERE id = 52;
UPDATE sportsmen SET position = '62' WHERE id = 53;
UPDATE sportsmen SET position = '67' WHERE id = 54;
UPDATE sportsmen SET position = '43' WHERE id = 55;
UPDATE sportsmen SET position = '48' WHERE id = 56;
UPDATE sportsmen SET position = '54' WHERE id = 57;
UPDATE sportsmen SET position = '68' WHERE id = 58;
UPDATE sportsmen SET position = '39' WHERE id = 59;
UPDATE sportsmen SET position = '65' WHERE id = 60;
UPDATE sportsmen SET position = '63' WHERE id = 61;
UPDATE sportsmen SET position = '98' WHERE id = 62;
UPDATE sportsmen SET position = '81' WHERE id = 63;
UPDATE sportsmen SET position = '76' WHERE id = 64;
UPDATE sportsmen SET position = '64' WHERE id = 65;
UPDATE sportsmen SET position = '47' WHERE id = 66;
UPDATE sportsmen SET position = '83' WHERE id = 67;
UPDATE sportsmen SET position = '100' WHERE id = 68;
UPDATE sportsmen SET position = '11' WHERE id = 69;
UPDATE sportsmen SET position = '90' WHERE id = 70;
UPDATE sportsmen SET position = '14' WHERE id = 71;
UPDATE sportsmen SET position = '25' WHERE id = 72;
UPDATE sportsmen SET position = '69' WHERE id = 73;
UPDATE sportsmen SET position = '80' WHERE id = 74;
UPDATE sportsmen SET position = '24' WHERE id = 75;
UPDATE sportsmen SET position = '49' WHERE id = 76;
UPDATE sportsmen SET position = '45' WHERE id = 77;
UPDATE sportsmen SET position = '2' WHERE id = 78;
UPDATE sportsmen SET position = '97' WHERE id = 79;
UPDATE sportsmen SET position = '53' WHERE id = 80;
UPDATE sportsmen SET position = '38' WHERE id = 81;
UPDATE sportsmen SET position = '71' WHERE id = 82;
UPDATE sportsmen SET position = '87' WHERE id = 83;
UPDATE sportsmen SET position = '23' WHERE id = 84;
UPDATE sportsmen SET position = '29' WHERE id = 85;
UPDATE sportsmen SET position = '13' WHERE id = 86;
UPDATE sportsmen SET position = '78' WHERE id = 87;
UPDATE sportsmen SET position = '1' WHERE id = 88;
UPDATE sportsmen SET position = '28' WHERE id = 89;
UPDATE sportsmen SET position = '70' WHERE id = 90;
UPDATE sportsmen SET position = '96' WHERE id = 91;
UPDATE sportsmen SET position = '74' WHERE id = 92;
UPDATE sportsmen SET position = '40' WHERE id = 93;
UPDATE sportsmen SET position = '52' WHERE id = 94;
UPDATE sportsmen SET position = '86' WHERE id = 95;
UPDATE sportsmen SET position = '56' WHERE id = 96;
UPDATE sportsmen SET position = '66' WHERE id = 97;
UPDATE sportsmen SET position = '18' WHERE id = 98;
UPDATE sportsmen SET position = '89' WHERE id = 99;
UPDATE sportsmen SET position = '77' WHERE id = 100;
